- op: replace
  path: "/metadata/name"
  value: example
- op: add
  path: "/spec/releases"
  value: quay.io/openshift-ota/openshift-cincinnati-test-public-manual
- op: add
  path: "/spec/graphDataImage"
  value: your-registry/your-repo/your-init-container
