apiVersion: updateservice.operator.openshift.io/v1
kind: UpdateService
metadata:
  name: example
spec:
  replicas: 1
  releases: quay.io/redhat/openshift-cincinnati-test-public-manual
  graphDataImage: your-registry/your-repo/your-init-container
